Feat:한줄 삭제 이펙트 구현#49
SWE-team11/tetris pull request #57
Opened 2022-04-20 14:54 UTC by joonyy

## 개발사항
raw가 쌓이면 white로 색이 변한 뒤, shiftDown하도록 구현.

### 이전 상황

#14 
---

## 추가사항

추가적으로 알아야하는 사항을 작성해주세요.

2022-04-20 15:15 UTC, KeisLuv5991 requested changes

2022-04-20 15:15 UTC, KeisLuv5991 commented on app/src/main/java/tetris/model/GameModel.java
> +        currentBlock = new IBlock();
롤백하기

2022-04-20 15:15 UTC, Istiopaxx commented on app/src/main/java/tetris/model/GameModel.java
> +
삭제 요망

2022-04-20 15:15 UTC, Istiopaxx commented on app/src/main/java/tetris/model/GameModel.java
> +
삭제 요망

2022-04-20 15:15 UTC, Istiopaxx commented on app/src/main/java/tetris/model/GameModel.java
> +                System.out.println("탈출");
삭제 요망

2022-04-20 15:57 UTC, KeisLuv5991 approved these changes, later dismissed

2022-04-20 16:13 UTC, KeisLuv5991 approved these changes

2022-04-20 16:13 UTC, merged

2022-04-21 01:53 UTC, sjsjsj1246 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR #57: Feat:한줄 삭제 이펙트 구현#49](https://trello.com/c/wkwNZlB3/97-pr-57-feat%ED%95%9C%EC%A4%84-%EC%82%AD%EC%A0%9C-%EC%9D%B4%ED%8E%99%ED%8A%B8-%EA%B5%AC%ED%98%8449)